<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	  <LangVersion>9.0</LangVersion>

	  <IsPackable>true</IsPackable>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Authors>Shantanu</Authors>
	  <Company>Veritas Software</Company>
	  <Description>Client for OnTheFlySettings endpoints.</Description>
	  <PackageProjectUrl>https://github.com/VeritasSoftware/OnTheFlySettings</PackageProjectUrl>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <RepositoryUrl>https://github.com/VeritasSoftware/OnTheFlySettings</RepositoryUrl>
	  <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
	  <PackageTags>asp net core client on the fly settings dynamic without restarting API application runtime</PackageTags>
	  <Version>1.0.0</Version>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
	  <FileVersion>1.0.0.0</FileVersion>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="System.Text.Json" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
