<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>

	  <IsPackable>true</IsPackable>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Authors>Shantanu</Authors>
	  <Company>Veritas Software</Company>
	  <Description>Library allows to read/update your settings on-the-fly, without re-starting your application. Supports .NET 6/7/8/9/10.</Description>
	  <PackageProjectUrl>https://github.com/VeritasSoftware/LiveHealthChecks</PackageProjectUrl>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <RepositoryUrl>https://github.com/VeritasSoftware/LiveHealthChecks</RepositoryUrl>
	  <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
	  <PackageTags>asp net core on the fly settings dynamic without restarting application at runtime</PackageTags>
	  <Version>1.0.0</Version>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
	  <FileVersion>1.0.0.0</FileVersion>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

	<ItemGroup>
		<!-- Include README -->
		<None Include=".\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<!-- Include images folder -->
		<None Include="Images\**" Pack="true" PackagePath="images\" />
	</ItemGroup>
</Project>
